### ISSUE TITLE
背景知識の整理

### ISSUE THREAD

**Issue by KuangyiZhu** [KuangyiZhu/ML_Survey#10]
- [x] ターゲティング広告
  - [x] YDN 広告管理の仕組み
  - [x] GDN 広告管理の仕組み
- [x] Conversion 計測の仕組み
- [x] Conversion 最適化の背景
  - [x] Gの定義
  - [x] Yの定義
  - [x] UX背景

**Comment by y-kzhu** [comment]
targetting adg
Yの仕組み

ターゲティング
http://promotionalads.yahoo.co.jp/online/course/ydn/targeting/overview.html

性別ターゲティングについて
年齢ターゲティングについて
サイトリターゲティングとは
サーチターゲティングの仕組みと設定
プレイスメントターゲティング

CVOの単位
https://help.marketing.yahoo.co.jp/ja/?p=1263
広告掲載方式
https://help.marketing.yahoo.co.jp/ja/?p=1261
ターゲティングの単位
https://help.marketing.yahoo.co.jp/ja/?p=1281/c/95,494,501,517/o/rnt?o=JP0871

UX
http://promotionalads.yahoo.co.jp/online/course/ydn/targeting/reference_1.html

メインターゲット以外に効率よくコンバージョンを獲得できている属性を見つけたら、その属性を新しい広告グループとして独立させ、その属性のユーザーに合わせた広告文を作成することで、コンバージョン獲得までの効率をさらに高めることが可能になります。

UX
http://promotionalads.yahoo.co.jp/online/course/ydn/targeting/rtg/noconv.html

http://promotionalads.yahoo.co.jp/service/ydn/

targeting exclusive list
http://promotionalads.yahoo.co.jp/support/release/2014/120301.html

becon conversion
http://docs.yahoo.co.jp/docs/info/terms/pixels.html
https://help.marketing.yahoo.co.jp/ja/?p=1355
コンバージョン測定はお客様のサイトにおいて、商品購入、サイト登録、コンテンツ購読、メールマガジン登録などの取引を完了したインターネットユーザーをトラッキングし、コンバージョン数、コンバージョン率、コンバージョンコストを算出する効果測定機能です。

お客様のサイト上の取引完了ページに、コンバージョン測定タグを正しく設置しておくと、訪問者が取引完了ページに到達したときに、コンバージョンが発生します。

訪問者のブラウザーがPC・スマートフォン・タブレットの場合はCookie情報、モバイル（フィーチャーフォン）の場合は固体識別番号を元に、その訪問者がお客様の出稿した広告をクリックしたかをチェックし30日間以内にクリックの履歴があれば有効なコンバージョンとしてカウントします。

**Comment by y-kzhu** [comment]
CVOの設定
http://promotionalads.yahoo.co.jp/support/release/2014/0820.html
CV率向上のユーザー行為
http://promotionalads.yahoo.co.jp/online/course/sponsor/reference/cvr_targeting.html
CV測定
http://promotionalads.yahoo.co.jp/online/course/adtech/tag_start.html
YDN CVO機能紹介
http://promotionalads.yahoo.co.jp/online/course/ydn/ydn/yco.html

**Comment by y-kzhu** [comment]
GDNのターゲティング設定について
https://support.google.com/adwords/answer/1209882?hl=ja
GDNのCVO設定について
https://support.google.com/adwords/answer/2472674?hl=ja
CVOについて
http://www.google.co.jp/intl/ja/adwords/conversionoptimizer/
GDN CVO機能
https://support.google.com/adwords/answer/2471188?hl=ja

**Comment by y-kzhu** [comment]
CPA
Cost Per Acquisition
成果報酬型広告、アフィリエイト広告における広告単価の指標で、成果一件あたりの支払額。
1回の商品／サービスに対する顧客獲得コストの略。
Webサイトの最終的な目標に対しての獲得コストを指す。
たとえば、1クリック100円でPPC広告をして、顧客獲得に100クリック必要だった場合、CPA（顧客獲得コスト）は10,000円になる。

CPA CTR 調整Bid（以下Bidと呼ぶ） CVの関係

Bid- CTR-　CV↑ CPAは↓
Bid- CTR-　CV↓ CPAは↑
Bid- CTR↑　CV- CPAは↑
Bid- CTR↓　CV- CPAは↓
Bid↑ CTR-  CV- CPA↑
Bid↓ CTR-  CV- CPA↓
Bid↑ CTR↑　CV- CPA↑
Bid↓ CTR↓　CV- CPA↓
Bid↑ CTR↓　CV- CPA↑　（imps↑ click数をみる）
Bid↓ CTR↑　CV- CPA↓　　（imps↓ click数をみる）
Bid↑ CTR↓　CV↑ CPA↑　（CTR↓だから）
Bid↑ CTR↓　CV↓ CPA↑　（CTR↓だから）
Bid↓ CTR↑　CV- CPA↓　　（imps↓ click数をみる）
Bid↓ CTR↑　CV↑ CPA↓　　imps↓
Bid↓ CTR↑　CV↓ CPA↓　　（click数は減っているから）
