### ISSUE TITLE
実験を計画する

### ISSUE THREAD

**Issue by KuangyiZhu** [KuangyiZhu/ML_Survey#2]
## 問題
-  評価方法
  - [x] ROC
  - [x]  cross-validation
  - [x]  背景を把握して他の可能な評価尺度を考える
- 利用するデーター
  - [x]  Yが発表した論文で利用されたデーター

**Comment by KuangyiZhu** [comment]
## 問題
*  評価方法
 * ROC
 * cross-validation
* 利用するデーター
 * 発表した論文を参照する

**Comment by KuangyiZhu** [comment]
つぎの行動としてテストデーターと学習データーを収集して、一回情報をみる。

**Comment by y-kzhu** [comment]
http://research-lab.yahoo.co.jp/ml/20140301_79.html
では、実データーを利用している。
評価単位は広告のCampaignである。（あまりよくない）
予測CVの精度のみ評価していた

**Comment by y-kzhu** [comment]
有意差の評価
https://bigdataeconometrics.wordpress.com/2013/12/28/statistical-significance-in-big-data/
